
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Guest user
 */
public class CountdownTimer extends javax.swing.JFrame {
///Variable declaration
    int countDownHours;
    int countDownMinutes;
    int countDownSeconds;

    /**
     * Creates new form CountdownTimer
     */
    public CountdownTimer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            countDownSeconds--;
            if (countDownSeconds <= 59 && countDownSeconds >= 10) {
                secondsValue.setText(String.valueOf(countDownSeconds));
            }
            else if (countDownSeconds < 10 && countDownSeconds >= 1) {
                secondsValue.setText("0" + countDownSeconds);
            }
            else{
                secondsValue.setText("0"+countDownSeconds);
                if(countDownHours >= 0 && countDownMinutes > 0){
                    countDownSeconds = 60;
                    countDownMinutes--;
                    if(countDownMinutes <= 59 && countDownMinutes >= 10){
                        minutesValue.setText(String.valueOf(countDownMinutes));
                    }
                    else if(countDownMinutes < 10){
                        minutesValue.setText("0" + countDownMinutes);
                    }
                    
                }
                else if(countDownHours > 0 && countDownMinutes == 0){
                    countDownHours--;
                    if(countDownHours <= 59 && countDownHours >= 10){
                        hoursValue.setText(String.valueOf(countDownHours));
                    }
                    else if(countDownHours < 10){
                        hoursValue.setText("0" + countDownHours);
                    }
                    countDownMinutes = 60;
                }
            }
            if(countDownHours == 0 && countDownMinutes == 0 && countDownSeconds == 0){
               timer.stop();
               JOptionPane.showMessageDialog(null,"TIME IS UP!","ALARM RINGING",INFORMATION_MESSAGE);
            }
        }
    });
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        addPresetTimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hoursValue = new javax.swing.JLabel();
        minutesValue = new javax.swing.JLabel();
        secondsValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setBackground(new java.awt.Color(204, 204, 204));
        start.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        start.setForeground(new java.awt.Color(0, 255, 0));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        pause.setBackground(new java.awt.Color(204, 204, 204));
        pause.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pause.setForeground(new java.awt.Color(51, 255, 0));
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        getContentPane().add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        previousButton.setBackground(new java.awt.Color(204, 204, 204));
        previousButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButton.setForeground(new java.awt.Color(51, 255, 0));
        previousButton.setText("<MENU");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        addPresetTimer.setBackground(new java.awt.Color(204, 204, 204));
        addPresetTimer.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addPresetTimer.setForeground(new java.awt.Color(0, 255, 0));
        addPresetTimer.setText("Add Preset Timer");
        addPresetTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPresetTimerActionPerformed(evt);
            }
        });
        getContentPane().add(addPresetTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("                            Time Remaining");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 90, 570, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText(":");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 0));
        jLabel4.setText(":");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 10, -1));

        hoursValue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        hoursValue.setForeground(new java.awt.Color(51, 255, 0));
        hoursValue.setText("jLabel6");
        getContentPane().add(hoursValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 120, 100, -1));

        minutesValue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        minutesValue.setForeground(new java.awt.Color(102, 255, 0));
        minutesValue.setText("jLabel5");
        getContentPane().add(minutesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        secondsValue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        secondsValue.setForeground(new java.awt.Color(102, 255, 0));
        secondsValue.setText("jLabel5");
        getContentPane().add(secondsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/countdown.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        setSize(new java.awt.Dimension(576, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        try {
            char a = hoursValue.getText().charAt(1);
            char b = minutesValue.getText().charAt(1);
            char c = secondsValue.getText().charAt(1);

            if (hoursValue.getText().charAt(0) == '0') {
                countDownHours = a - '0';
                
            } else {
                countDownHours = Integer.parseInt(hoursValue.getText());
            }
            if (minutesValue.getText().charAt(0) == '0') {
                countDownMinutes = b - '0';
                
            } else {
                countDownMinutes = Integer.parseInt(minutesValue.getText());
            }
            if (secondsValue.getText().charAt(0) == '0') {
                countDownSeconds = c - '0';

            } else {
                countDownSeconds = Integer.parseInt(secondsValue.getText());
            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "MESSAGE", ERROR_MESSAGE);
        }
        timer.start();

    }//GEN-LAST:event_startActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        if(pause.getText().equals("Pause")){
           pause.setText("resume");
           timer.stop();
        }
        else if(pause.getText().equals("resume")){
            pause.setText("Pause");
            timer.restart();
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        SetTime st = new SetTime();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void addPresetTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPresetTimerActionPerformed
        SetTime st = new SetTime();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addPresetTimerActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            
            //hoursValue.setText(Int.parseInt(st.getHours()));
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(CountdownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(CountdownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(CountdownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(CountdownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
           

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CountdownTimer().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPresetTimer;
    public javax.swing.JLabel hoursValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel minutesValue;
    private javax.swing.JButton pause;
    private javax.swing.JButton previousButton;
    public javax.swing.JLabel secondsValue;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
