
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guest user
 */
public class LongBreakTab extends javax.swing.JFrame {
    private int longBreakSeconds = 60;
    private int longBreakMinutes = 10;

    /**
     * Creates new form LongBreakTab
     */
    public LongBreakTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(longBreakMinutes == 10){
                longBreakMinutes--;
                longBreakMinutesLabel.setText(String.valueOf(longBreakMinutes));
            }
            longBreakSeconds--;
            if (longBreakSeconds >= 10) {
                longBreakSecondsLabel.setText(String.valueOf(longBreakSeconds));
            }
            else {
                longBreakSecondsLabel.setText("0" + longBreakSeconds);
                if(longBreakSeconds == 0) {
                    longBreakMinutes--;
                    if (longBreakMinutes >= 10) {
                        longBreakMinutesLabel.setText(String.valueOf(longBreakMinutes));
                    }
                    else {
                        longBreakMinutesLabel.setText("0" + longBreakMinutes);
                    }
                    longBreakSeconds = 60;
                }
            }
            if(longBreakMinutes == 0 && longBreakSeconds == 0){
                JOptionPane.showMessageDialog(null,"BREAK TIMER OVER!","ALARM RINGING",INFORMATION_MESSAGE);
            }
        }
    });
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousButton = new javax.swing.JButton();
        pomodoroButton = new javax.swing.JButton();
        shortBreakButton = new javax.swing.JButton();
        longBreakButton = new javax.swing.JButton();
        longBreakMinutesLabel = new javax.swing.JLabel();
        longBreakSecondsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startPomodoroButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previousButton.setBackground(new java.awt.Color(0, 153, 0));
        previousButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButton.setForeground(new java.awt.Color(255, 255, 255));
        previousButton.setText("<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pomodoroButton.setBackground(new java.awt.Color(0, 153, 0));
        pomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroButton.setText("Pomodoro");
        pomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        shortBreakButton.setBackground(new java.awt.Color(0, 153, 0));
        shortBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        shortBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        shortBreakButton.setText("Short Break");
        shortBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shortBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        longBreakButton.setBackground(new java.awt.Color(0, 153, 0));
        longBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        longBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        longBreakButton.setText("Long Break");
        longBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(longBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        longBreakMinutesLabel.setBackground(new java.awt.Color(255, 255, 255));
        longBreakMinutesLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        longBreakMinutesLabel.setForeground(new java.awt.Color(255, 255, 255));
        longBreakMinutesLabel.setText("10");
        getContentPane().add(longBreakMinutesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        longBreakSecondsLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        longBreakSecondsLabel.setForeground(new java.awt.Color(255, 255, 255));
        longBreakSecondsLabel.setText("00");
        getContentPane().add(longBreakSecondsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 37, -1));

        startPomodoroButton.setBackground(new java.awt.Color(0, 153, 0));
        startPomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        startPomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        startPomodoroButton.setText("START");
        startPomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startPomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Time for a longer break!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 260, 240, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/study.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 690, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shortBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortBreakButtonActionPerformed
        ShortBreakTab sbt = new ShortBreakTab();
        sbt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shortBreakButtonActionPerformed

    private void pomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodoroButtonActionPerformed
        PomodoroTimer pt = new PomodoroTimer();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pomodoroButtonActionPerformed

    private void longBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longBreakButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longBreakButtonActionPerformed

    private void startPomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPomodoroButtonActionPerformed
        switch (startPomodoroButton.getText()) {
            case "START":
                timer.start();
                startPomodoroButton.setText("PAUSE");
                break;
            case "PAUSE":
                timer.stop();
                startPomodoroButton.setText("RESUME");
                break;
            case "RESUME":
                timer.restart();
                startPomodoroButton.setText("PAUSE");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_startPomodoroButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        PomodoroTimer pt = new PomodoroTimer();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(LongBreakTab.class.getName()).log(java.util.logging.Level.SEVERE,pomodoroButton);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LongBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LongBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LongBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LongBreakTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton longBreakButton;
    private javax.swing.JLabel longBreakMinutesLabel;
    private javax.swing.JLabel longBreakSecondsLabel;
    private javax.swing.JButton pomodoroButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton shortBreakButton;
    private javax.swing.JButton startPomodoroButton;
    // End of variables declaration//GEN-END:variables
}
