
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guest user
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        stopwatchRadioButton = new javax.swing.JRadioButton();
        countdowntimerRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pomodorotimerRadioButton = new javax.swing.JRadioButton();
        presettimerRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(stopwatchRadioButton);
        stopwatchRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stopwatchRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        stopwatchRadioButton.setText("Stopwatch");
        stopwatchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopwatchRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopwatchRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 98, -1));

        buttonGroup1.add(countdowntimerRadioButton);
        countdowntimerRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countdowntimerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        countdowntimerRadioButton.setText("CountDown Timer");
        countdowntimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countdowntimerRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(countdowntimerRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        okButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIMER&STOPWATCH APPLICATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 360, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cape Peninsula University of Technology");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        buttonGroup1.add(pomodorotimerRadioButton);
        pomodorotimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pomodorotimerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        pomodorotimerRadioButton.setText("Pomodoro Timer");
        pomodorotimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodorotimerRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pomodorotimerRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        buttonGroup1.add(presettimerRadioButton);
        presettimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        presettimerRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        presettimerRadioButton.setText(" Preset Timer");
        getContentPane().add(presettimerRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage your time efficiently with our easy to use stopwatch and timer app");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopwatchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopwatchRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopwatchRadioButtonActionPerformed

    private void countdowntimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countdowntimerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countdowntimerRadioButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(stopwatchRadioButton.isSelected()== true){
            Stopwatch sw = new Stopwatch();
            sw.setVisible(true);
            this.dispose();
        }
        else if(countdowntimerRadioButton.isSelected()== true){
            SetTime st = new SetTime();
            st.setVisible(true);
            this.dispose();
        }
        else if(pomodorotimerRadioButton.isSelected()== true){
            PomodoroTimer pt = new PomodoroTimer();
            pt.setVisible(true);
            this.dispose();
        }
        else if(presettimerRadioButton.isSelected() == true){
            PresetTimer pst = new PresetTimer();
            pst.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE SELECT ONE OF THE OPTIONS!","Message",INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void pomodorotimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodorotimerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pomodorotimerRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton countdowntimerRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton pomodorotimerRadioButton;
    private javax.swing.JRadioButton presettimerRadioButton;
    private javax.swing.JRadioButton stopwatchRadioButton;
    // End of variables declaration//GEN-END:variables
}
