
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guest user
 */
public class PomodoroTimer extends javax.swing.JFrame {

    private int pomodoroSeconds = 60;
    private int pomodoroMinutes = 30;

    /**
     * Creates new form PomodoroTimer
     */
    public PomodoroTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pomodoroButton = new javax.swing.JButton();
        shortBreakButton = new javax.swing.JButton();
        longBreakButton = new javax.swing.JButton();
        pomodoroMinutesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pomodoroSecondsLabel = new javax.swing.JLabel();
        startPomodoroButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        addTask = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pomodoroButton.setBackground(new java.awt.Color(153, 0, 153));
        pomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        pomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroButton.setText("Pomodoro");
        pomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 42, -1, -1));

        shortBreakButton.setBackground(new java.awt.Color(153, 0, 153));
        shortBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        shortBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        shortBreakButton.setText("Short Break");
        shortBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shortBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        longBreakButton.setBackground(new java.awt.Color(153, 0, 153));
        longBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        longBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        longBreakButton.setText("Long Break");
        longBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(longBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        pomodoroMinutesLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pomodoroMinutesLabel.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroMinutesLabel.setText("30");
        getContentPane().add(pomodoroMinutesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        pomodoroSecondsLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pomodoroSecondsLabel.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroSecondsLabel.setText("00");
        getContentPane().add(pomodoroSecondsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 66, -1));

        startPomodoroButton.setBackground(new java.awt.Color(153, 0, 153));
        startPomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        startPomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        startPomodoroButton.setText("Start");
        startPomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startPomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 93, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 264, 37, -1));

        textLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textLabel.setText("Time to focus on your current  task");
        getContentPane().add(textLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 230, -1));

        previousButton.setBackground(new java.awt.Color(153, 0, 153));
        previousButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButton.setForeground(new java.awt.Color(255, 255, 255));
        previousButton.setText("<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 299, 37, -1));

        addTask.setBackground(new java.awt.Color(153, 0, 153));
        addTask.setText("ADD TASK");
        getContentPane().add(addTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, 98, -1));

        okButton.setBackground(new java.awt.Color(153, 0, 153));
        okButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pomodoro.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(pomodoroMinutes == 30){
                pomodoroMinutes--;
                pomodoroMinutesLabel.setText(String.valueOf(pomodoroMinutes));
            }
            pomodoroSeconds--;
            if(pomodoroSeconds >= 10 && pomodoroSeconds <= 59){
                pomodoroSecondsLabel.setText(String.valueOf(pomodoroSeconds));
            }
            else if(pomodoroSeconds < 10 && pomodoroSeconds > 0){
                pomodoroSecondsLabel.setText(String.valueOf("0"+pomodoroSeconds));
            }
            else{
               
               pomodoroSeconds = 60;
               if(pomodoroMinutes < 10 && pomodoroMinutes >0){
                    pomodoroMinutesLabel.setText(String.valueOf("0"+pomodoroMinutes));
                    pomodoroSecondsLabel.setText(String.valueOf("00"));
                    pomodoroMinutes--;
                    pomodoroMinutesLabel.setText(String.valueOf("0"+pomodoroMinutes));
               }
               else{
                    pomodoroMinutesLabel.setText(String.valueOf(String.valueOf(pomodoroMinutes)));
                    pomodoroSecondsLabel.setText(String.valueOf("00"));
                    pomodoroMinutes--;
                    pomodoroMinutesLabel.setText(String.valueOf(String.valueOf(pomodoroMinutes)));
               }
           }
           /* if(pomodoroMinutes == 30){
                pomodoroMinutes--;
                pomodoroMinutesLabel.setText(String.valueOf(pomodoroMinutes));
            }
            pomodoroSeconds--;
            if (pomodoroSeconds >= 10) {
                pomodoroSecondsLabel.setText(String.valueOf(pomodoroSeconds));
            }
            else {
                pomodoroSecondsLabel.setText("0" + pomodoroSeconds);
                if(pomodoroSeconds == 0) {                   
                    if (pomodoroMinutes >= 10) {
                        pomodoroMinutesLabel.setText(String.valueOf(pomodoroMinutes));
                        pomodoroSecondsLabel.setText(String.valueOf("0"+pomodoroSeconds));
                        pomodoroMinutes--;
                    }
                    else {
                        pomodoroMinutesLabel.setText("0" + pomodoroMinutes);
                    }
                    pomodoroSeconds = 60;
                }
            }*/
        }
    });

    private void pomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodoroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pomodoroButtonActionPerformed

    private void shortBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortBreakButtonActionPerformed
        ShortBreakTab sbt = new ShortBreakTab();
        sbt.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_shortBreakButtonActionPerformed

    private void longBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longBreakButtonActionPerformed
        LongBreakTab lbt = new LongBreakTab();
        lbt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_longBreakButtonActionPerformed

    private void startPomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPomodoroButtonActionPerformed
        switch (startPomodoroButton.getText()) {
            case "Start":
                timer.start();
                startPomodoroButton.setText("Pause");
                break;
            case "Pause":
                timer.stop();
                startPomodoroButton.setText("Resume");
                break;
            case "Resume":
                timer.restart();
                startPomodoroButton.setText("Pause");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_startPomodoroButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        MenuPage mp = new MenuPage();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(addTask.isSelected() == true){
            String input = "";
            input = JOptionPane.showInputDialog(this,"What are you working on?");
            textLabel.setText("Current Task: "+ input);
        }
    }//GEN-LAST:event_okButtonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(PomodoroTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(PomodoroTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(PomodoroTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(PomodoroTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new PomodoroTimer().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton longBreakButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton pomodoroButton;
    private javax.swing.JLabel pomodoroMinutesLabel;
    private javax.swing.JLabel pomodoroSecondsLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton shortBreakButton;
    private javax.swing.JButton startPomodoroButton;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
