
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guest user
 */
public class PresetTimer extends javax.swing.JFrame {
    
    
    
    private String presetSeconds;
    private String presetMinutes;
    int secondsValue;
    int minutesValue;
    int add = 0;
    
    /**
     * Creates new form PresetTimer
     */
    public PresetTimer() {
       /* try{
            Double.parseDouble(presetMinutes);
            Double.parseDouble(presetSeconds);
    }
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this,"Invalid Time Format!","NumberFormat Exception",ERROR_MESSAGE);
    }
    catch(NullPointerException e){
        JOptionPane.showMessageDialog(this,"Oops,Something went wrong!","NullPointer Exception",ERROR_MESSAGE);
    }*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           if(secondsValue == 0){
               if(minutesValue != 0){
                    minutesValue--;
               }
               secondsValue = 60;
               labelforSeconds.setText("00");
               secondsValue--;
               labelforSeconds.setText(String.valueOf(secondsValue));
               if(minutesValue > 9 && minutesValue <= 59){
                   labelforMinutes.setText(String.valueOf(minutesValue));
               }
               else if(minutesValue < 10 && minutesValue > 0){
                   labelforMinutes.setText("0"+minutesValue);
               }
               else{
                   minutesValue--;
                   //labelforSeconds.setText("00");
               }
           }
           else{
               secondsValue--;
               if(secondsValue > 9 && secondsValue <= 59){
                   labelforSeconds.setText(String.valueOf(secondsValue));
               }
               else if(secondsValue < 10 && secondsValue > 0){
                   labelforSeconds.setText("0"+secondsValue);
                   
                 
               }
               else{
                   labelforSeconds.setText("00");
              /* if(secondsValue == 0) {
                    secondsValue = 60;
                    secondsValue--;
                    minutesValue--;
                    labelforSeconds.setText(String.valueOf(secondsValue));
                    if (minutesValue >= 10) {
                        labelforMinutes.setText(String.valueOf(minutesValue));
                        minutesValue--;*/
                    }  
               }
           }
        
        
        
            /*secondsValue--;
            if (secondsValue >= 10) {
                labelforSeconds.setText(String.valueOf(secondsValue));
            }
            else {
                labelforSeconds.setText("0" + secondsValue);
                if(secondsValue == 0) {
                    secondsValue = 60;
                    secondsValue--;
                    minutesValue--;
                    labelforSeconds.setText(String.valueOf(secondsValue));
                    if (minutesValue >= 10) {
                        labelforMinutes.setText(String.valueOf(minutesValue));
                        minutesValue--;
                    }
                    else {
                        labelforMinutes.setText("0" + minutesValue);
                    }
                    //secondsValue = 60;
                }
                else{
                    secondsValue--;
                    if (secondsValue >= 10) {
                    labelforSeconds.setText(String.valueOf(secondsValue));
                    }
                    else{
                    labelforSeconds.setText("0" + secondsValue);
                    }
                }
            }
        }*/
        
    });
    
     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        presetTimerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        minutesTextField = new javax.swing.JTextField();
        secondsTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addRadioButton = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelforMinutes = new javax.swing.JLabel();
        labelforSeconds = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previousButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        previousButton.setText("<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 116, 0, -1));
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 47, 249, 24));
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 116, 139, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 112, 37, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 157, 37, -1));

        startButton.setBackground(new java.awt.Color(0, 204, 204));
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 240, 98, 37));

        resetButton.setBackground(new java.awt.Color(255, 255, 0));
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 240, 86, 37));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRESET TIMER NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));
        getContentPane().add(presetTimerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 47, 79, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTER TIME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));
        getContentPane().add(minutesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 189, 71, -1));
        getContentPane().add(secondsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 189, 71, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("minutes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 71, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("seconds");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 156, 71, -1));

        addRadioButton.setBackground(new java.awt.Color(102, 102, 102));
        addRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        addRadioButton.setText("add");
        getContentPane().add(addRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 98, -1));

        addButton.setBackground(new java.awt.Color(102, 102, 102));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD/EDIT PRESET TIMER");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, -1, 65));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        labelforMinutes.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        labelforMinutes.setForeground(new java.awt.Color(255, 255, 255));
        labelforMinutes.setPreferredSize(new java.awt.Dimension(50, 50));

        labelforSeconds.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        labelforSeconds.setForeground(new java.awt.Color(255, 255, 255));
        labelforSeconds.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel8.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelforMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelforSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelforMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelforSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 77, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transparent.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -190, 820, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       
        if(addRadioButton.isSelected() == true){
            String input = "";
            input = JOptionPane.showInputDialog(this,"Preset Timer Name");
            presetTimerName.setText(input);
        }
        
        presetMinutes = minutesTextField.getText();
        presetSeconds = secondsTextField.getText();
        if (presetMinutes.isBlank() || presetSeconds.isBlank()) {
            //throw new ArithmeticException("INVALID TIME");
            JOptionPane.showMessageDialog(this, "ENTER VALUES FOR YOUR TIME", "MESSAGE", ERROR_MESSAGE);
        } 
        
        
        
        else{
            try{
           
                if(Integer.parseInt(presetMinutes) >= 60 || Integer.parseInt(presetSeconds) >= 60){
                    if(Integer.parseInt(presetMinutes) < 0 || Integer.parseInt(presetSeconds) < 0){
                        throw new ArithmeticException("INVALID TIME");
                    }
                }

                if (Integer.parseInt(presetMinutes) < 10 && Integer.parseInt(presetMinutes) >= 0) {
                    labelforMinutes.setText("0" + presetMinutes);
                } else {
                    labelforMinutes.setText(String.valueOf(presetMinutes));
                }

                //seconds = Double.parseDouble(st.getSeconds());
                if (Integer.parseInt(presetSeconds) < 10 && Integer.parseInt(presetSeconds) >= 0) {
                    labelforSeconds.setText("0" + labelforSeconds);
                }else {
                    labelforSeconds.setText(String.valueOf(presetSeconds));
                }
            }
            catch(NullPointerException e){
                JOptionPane.showMessageDialog(this,"Oops,Something went wrong!","NullPointer Exception",ERROR_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Invalid Time Format!","NumberFormat Exception",ERROR_MESSAGE);
            }
            catch(ArithmeticException e){
                JOptionPane.showMessageDialog(this,"max value for minutes and seconds is 59 and max value for hours is 24!","MESSAGE",ERROR_MESSAGE);
            }
        }
        
        minutesValue = Integer.parseInt(presetMinutes);
        secondsValue = Integer.parseInt(presetSeconds);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(startButton.getText().equals("START")){
            timer.start();
            startButton.setText("STOP");
        }
        else if(startButton.getText().equals("STOP")){
            timer.stop();
            startButton.setText("RESUME");
        }  
        else{
            timer.restart();
            startButton.setText("STOP");
        }
    
    }//GEN-LAST:event_startButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        labelforMinutes.setText("");
        labelforSeconds.setText("");
        timer.stop();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        MenuPage mp = new MenuPage();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresetTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresetTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresetTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresetTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresetTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton addRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelforMinutes;
    private javax.swing.JLabel labelforSeconds;
    private javax.swing.JTextField minutesTextField;
    private javax.swing.JTextField presetTimerName;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField secondsTextField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
