
import java.awt.Font;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Guest user
 */
public class SetTime extends javax.swing.JFrame {

    private String hours;
    private String minutes;
    private String seconds;

    public String getHours() {
        return hours;
    }

    public String getMinutes() {
        return minutes;
    }

    public String getSeconds() {
        return seconds;
    }

    /**
     * Creates new form SetTime
     */

    public SetTime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hours_label = new javax.swing.JLabel();
        minutes_label = new javax.swing.JLabel();
        seconds_label = new javax.swing.JLabel();
        hoursText = new javax.swing.JTextField();
        minutesText = new javax.swing.JTextField();
        secondsText = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hours_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hours_label.setText("Hours :");

        minutes_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minutes_label.setText("Minutes :");

        seconds_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seconds_label.setText("Seconds :");

        hoursText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hoursText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursTextActionPerformed(evt);
            }
        });

        minutesText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minutesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesTextActionPerformed(evt);
            }
        });

        secondsText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsTextActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        previousButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButton.setText("<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previousButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(okButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(hoursText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(minutesText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(hours_label)
                                    .addGap(86, 86, 86)
                                    .addComponent(minutes_label))))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seconds_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(secondsText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 113, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousButton)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutes_label)
                    .addComponent(hours_label)
                    .addComponent(seconds_label))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(okButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoursTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursTextActionPerformed
        hoursText.setFont(new Font("Tahoma", Font.BOLD, 36));
    }//GEN-LAST:event_hoursTextActionPerformed

    private void minutesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesTextActionPerformed
        minutesText.setFont(new Font("Tahoma", Font.BOLD, 36));
    }//GEN-LAST:event_minutesTextActionPerformed

    private void secondsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondsTextActionPerformed
        secondsText.setFont(new Font("Tahoma", Font.BOLD, 36));
    }//GEN-LAST:event_secondsTextActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        hours = hoursText.getText();
        minutes = minutesText.getText();
        seconds = secondsText.getText();
        if (hours.isBlank() || minutes.isBlank() || seconds.isBlank()) {
            //throw new ArithmeticException("INVALID TIME");
            JOptionPane.showMessageDialog(this, "INVALID TIME", "MESSAGE", ERROR_MESSAGE);
        } 
        
        
        
        else {

            try{
                if(Double.parseDouble(hours) >= 25 || Double.parseDouble(minutes) >= 60 || Double.parseDouble(seconds) >= 60){
                    throw new ArithmeticException("INVALID TIME");
                }
                CountdownTimer cdt = new CountdownTimer();
                if (Double.parseDouble(hours) < 10) {
                    cdt.hoursValue.setText("0" + hours);
                } else {
                    cdt.hoursValue.setText("0" + hours);
                }

                if (Double.parseDouble(minutes) < 10) {
                    cdt.minutesValue.setText("0" + minutes);
                } else {
                    cdt.minutesValue.setText(String.valueOf(minutes));
                }

                //seconds = Double.parseDouble(st.getSeconds());
                if (Double.parseDouble(seconds) < 10) {
                    cdt.secondsValue.setText("0" + seconds);
                } else {
                    cdt.secondsValue.setText(String.valueOf(seconds));
                }
                cdt.setVisible(true);
                this.dispose();
            }
            catch(NullPointerException e){
                JOptionPane.showMessageDialog(this,"Oops,Something went wrong!","NullPointer Exception",ERROR_MESSAGE);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Invalid Time Format!","NumberFormat Exception",ERROR_MESSAGE);
            }
            catch(ArithmeticException e){
                JOptionPane.showMessageDialog(this,"max value for minutes and seconds is 59 and max value for hours is 24!","MESSAGE",ERROR_MESSAGE);
            }
            
    }
        

    }//GEN-LAST:event_okButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        MenuPage page = new MenuPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hoursText;
    private javax.swing.JLabel hours_label;
    private javax.swing.JTextField minutesText;
    private javax.swing.JLabel minutes_label;
    private javax.swing.JButton okButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField secondsText;
    private javax.swing.JLabel seconds_label;
    // End of variables declaration//GEN-END:variables

    /* String getHours() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
}
