
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Guest user
 */
public class ShortBreakTab extends javax.swing.JFrame {
    private int shortBreakSeconds = 60;
    private int shortBreakMinutes = 1;
    /**
     * Creates new form ShortBreakTab
     */
    public ShortBreakTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(shortBreakMinutes == 1){
                shortBreakMinutes--;
                shortBreakMinutesLabel.setText("0" + shortBreakMinutes);
            }
            shortBreakSeconds--;
            if (shortBreakSeconds >= 10) {
                shortBreakSecondsLabel.setText(String.valueOf(shortBreakSeconds));
            }
            else {
                shortBreakSecondsLabel.setText("0" + shortBreakSeconds);
                if(shortBreakSeconds == 0) {
                    shortBreakMinutes--;
                    if (shortBreakMinutes >= 10) {
                        shortBreakMinutesLabel.setText(String.valueOf(shortBreakMinutes));
                    }
                    else {
                        shortBreakMinutesLabel.setText("0" + shortBreakMinutes);
                    }
                    
                shortBreakSeconds = 60;
                }
            }if(shortBreakMinutes == 0 && shortBreakSeconds == 0){
                timer.stop();
                JOptionPane.showMessageDialog(null,"BREAK TIMER OVER!","ALARM RINGING",INFORMATION_MESSAGE);
                }
           
        }
    });
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pomodoroButton = new javax.swing.JButton();
        shortBreakButton = new javax.swing.JButton();
        longBreakButton = new javax.swing.JButton();
        shortBreakMinutesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        shortBreakSecondsLabel = new javax.swing.JLabel();
        startPomodoroButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pomodoroButton.setBackground(new java.awt.Color(153, 0, 153));
        pomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        pomodoroButton.setText("Pomodoro");
        pomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        shortBreakButton.setBackground(new java.awt.Color(153, 0, 153));
        shortBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        shortBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        shortBreakButton.setText("Short Break");
        shortBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shortBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        longBreakButton.setBackground(new java.awt.Color(153, 0, 153));
        longBreakButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        longBreakButton.setForeground(new java.awt.Color(255, 255, 255));
        longBreakButton.setText("Long Break");
        longBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longBreakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(longBreakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        shortBreakMinutesLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        shortBreakMinutesLabel.setForeground(new java.awt.Color(102, 0, 102));
        shortBreakMinutesLabel.setText("01");
        getContentPane().add(shortBreakMinutesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+24));
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 40, -1));

        shortBreakSecondsLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        shortBreakSecondsLabel.setForeground(new java.awt.Color(102, 0, 102));
        shortBreakSecondsLabel.setText("00");
        getContentPane().add(shortBreakSecondsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        startPomodoroButton.setBackground(new java.awt.Color(153, 0, 153));
        startPomodoroButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        startPomodoroButton.setForeground(new java.awt.Color(255, 255, 255));
        startPomodoroButton.setText("START");
        startPomodoroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPomodoroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startPomodoroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Take a short break and relax yourself. You got this!!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 460, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/city.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -600, 630, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PomodoroTimer pt = new PomodoroTimer();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodoroButtonActionPerformed
        PomodoroTimer pt = new PomodoroTimer();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pomodoroButtonActionPerformed

    private void shortBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortBreakButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortBreakButtonActionPerformed

    private void longBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longBreakButtonActionPerformed
        LongBreakTab lbt = new LongBreakTab();
        lbt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_longBreakButtonActionPerformed

    private void startPomodoroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPomodoroButtonActionPerformed
        switch (startPomodoroButton.getText()) {
            case "START":
                timer.start();
                startPomodoroButton.setText("PAUSE");
                break;
            case "PAUSE":
                timer.stop();
                startPomodoroButton.setText("RESUME");
                break;
            case "RESUME":
                timer.restart();
                startPomodoroButton.setText("PAUSE");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_startPomodoroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortBreakTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortBreakTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton longBreakButton;
    private javax.swing.JButton pomodoroButton;
    private javax.swing.JButton shortBreakButton;
    private javax.swing.JLabel shortBreakMinutesLabel;
    private javax.swing.JLabel shortBreakSecondsLabel;
    private javax.swing.JButton startPomodoroButton;
    // End of variables declaration//GEN-END:variables
}
